apiVersion: v1
kind: Pod 
metadata:
  name: pod-with-empty-dir
spec:
  restartPolicy: Never
  containers:
  - name: ubuntu-container
    image: ubuntu
    env:
    - name: host
      value: "google.com"
    resources:
      requests:
        cpu: "0.5"
        memory: "100Mi"
      limits: 
        cpu: "1"
        memory: "200Mi"
    volumeMounts:
    - name: data-volume
      mountPath: /data
    command: ["sleep"]
    args: ["3600"]
  volumes:
  - name: data-volume
    emptyDir:
      medium: Memory