apiVersion: v1
kind: Pod
metadata:
  name: busyboxab
  namespace: default
spec:
  containers:
  - name: busy1
    image: busybox
    command:
    - sleep 
    - "3600"
    volumeMounts:
    - mountPath: /somedir
      name: my-volume
  volumes:
  - name: my-volume
    emptyDir: {}
