apiVersion: v1
kind: Pod
metadata:
  name: command-env
  namespace: rishikesh
  labels:
    purpose: demonstrate-command-env
spec:
  containers:
  - name: command-demo-env
    image: debian
    env:
    - name: web
      value: "google.com"
    command: ["/bin/ping"]
    args: ["$(web)"]
    resources:
      limits: 
        memory: "100Mi"
        cpu: "100m"
      requests:
        cpu: "50m"
        memory: "50Mi"
  restartPolicy: OnFailure
