apiVersion: v1
kind: Pod
metadata:
  name: pod-with-expose
spec:
  containers:
  - name: pod-with-expose
    image: nginx
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "100Mi"
        cpu: "50m"
      limits:
        memory: "200Mi"
        cpu: "100m"
