apiVersion: v1
kind: Pod
metadata:
  name: command-env
  namespace: rishikesh
  labels:
    purpose: demonstrate-command-env
spec:
  containers:
  - name: command-demo-env
    image: debian
    env:
    - name: MESSAGE
      value: "Hello World"
    command: ["/bin/echo"]
    args: ["$(MESSAGE)"]
  restartPolicy: OnFailure
