apiVersion: v1
kind: Pod
metadata:
  name: command-demo
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: command-demo-container
    image: debian
    command: ["printenv"]
    args: ["HOSTNAME", "KUBERNETES_PORT"]
    resources:
      limits:
        memory = "500Mi"
        cpu= "100m"
      requests:
        memory: "100Mi"
        cpu: "50m"
  restartPolicy: OnFailure
