apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod
spec:
  containers:
  - name: secret-container
    image: busybox
    command: ["/bin/sh","-c","cat /etc/appconfig/private-key"]
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/appconfig
  volumes:
  - name: secret-volume
    secret:
      secretName: test-key-secret
