apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
  namespace: configmap-test
spec:
  containers:
  - name: secret-container
    image: k8s.gcr.io/busybox
    command: [ "/bin/sh", "-c", "env" ]
    envFrom:
    - secretRef:
        name: test-secret
